## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=people,dc=teilar,dc=gr
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:

## Environment

development:
  host: ldap.teilar.gr
  port: 389
  attribute: mail
  base: ou=people,dc=teilar,dc=gr
  #encoding: utf8
  #admin_user: cn=admin,dc=esc
  #admin_password: admin_password
  ssl: false
  # <<: *AUTHORIZATIONS

test:
  # <<: *AUTHORIZATIONS

production:
  host: ldap.teilar.gr
  port: 389
  attribute: mail
  base: ou=people,dc=teilar,dc=gr
  #admin_user: cn=admin,dc=test,dc=com
  #admin_password: admin_password
  ssl: false
  # <<: *AUTHORIZATIONS
