## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=people,dc=teilar,dc=gr
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - mail=cs3171@teilar.gr,ou=people,dc=teilar,dc=gr
    #- uid=3171,ou=people,dc=teilar,dc=gr
    #- cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["cs3171", "mail=esc,ou=groups,dc=test,dc=com"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    #businessCategory:
    #sn: ΦΑΛΕΓΚΟΣ
    #employeeType
    #description: "ΤΜΗΜΑ ΠΛΗΡΟΦΟΡΙΚΗΣ"
    #displayName: ΑΝΤΩΝΙΟΣ ΦΑΛΕΓΚΟΣ
    #uid: 3171
    #objectClass: inetOrgPerson
    #authorizationRole: postsAdmin

## Environment

development:
  host: ldap.teilar.gr
  port: 389
  attribute: mail
  base: ou=people,dc=teilar,dc=gr
  #encoding: utf8
  #admin_user: cn=admin,dc=esc
  #admin_password: admin_password
  ssl: false
  # <<: *AUTHORIZATIONS

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls
  # <<: *AUTHORIZATIONS

production:
  host: localhost
  port: 636
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: start_tls
  # <<: *AUTHORIZATIONS
